name: 'Tech Weekly Feed Bot'

on:
  push:
    branches:
      - main

jobs:
  feed-processor:
    name: Dev Tricks processor
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@main
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Build Docs
        run: npm run docs:build
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs/.vitepress/dist # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
